### ISSUE TITLE
Structure of nested types

### ISSUE THREAD

**Issue by fab1an** [reactjs/react-docgen#103]
A normal proptype has the following report-structure

``` javascript
"password": {
    "type": {
         "name": "string"
    },
    "required": true,
    "description": ""
},
```

Whereas a nested type (in an `arrayOf`) looks like this:

``` javascript
"notifications": {
    "type": {
        "name": "arrayOf",
        "value": {
            "name": "string"
        }
    },
    "required": true,
    "description": ""
}
```

The inner type has no nested "type" Object), so I constantly have to do this to fix the structure:

``` javascript
function fixChildType(childType) {
    return {
        required: childType.required,
        type: {
            name: childType.name,
            raw: childType.raw,
            value: childType.value
        }
    };
}
```

**Comment by fkling** [comment]
Sorry, I thought I commented on this one.

I think you are comparing two different things here. The outer object is actually a prop. A prop has a type, description and can be mandatory. The type itself can contain subtypes but because types *are* types, they don't need a `type` field.

But I certainly think that this is a bit confusing and might need some restructuring. At the end of the day, it's important that the structure is easy to process.
