### ISSUE TITLE
feature request - allow for using only export default when multiple exports exist in a file

### ISSUE THREAD

**Issue by natehardy** [reactjs/react-docgen#160]
When using react and redux, it is common to export both the redux connected component and the plain component as well. react-docgen doesn't allow  for multiple exports. It would be nice to pass in a flag to config to allow for multiple exports and only use the default one.

**Comment by fkling** [comment]
We do have the [`findAllExportedComponentDefinitions`](https://github.com/reactjs/react-docgen/blob/master/src/resolver/findAllExportedComponentDefinitions.js) resolver. Doesn't that work for your use case?

**Comment by redak105** [comment]
I have same problem with redux. I have JS files with only functions, because redux definition of actions and reducers. Is there possibility to export this files in your framework?

example:
`
/*
 * action types
 */
export const ADD_TODO = 'ADD_TODO'
export const TOGGLE_TODO = 'TOGGLE_TODO'
export const SET_VISIBILITY_FILTER = 'SET_VISIBILITY_FILTER'

/*
 * action creators
 */
export function addTodo(text) {
  return { 
     type: ADD_TODO, text
   }
}

export function toggleTodo(index) {
  return { 
      type: TOGGLE_TODO, index 
  }
}`

**Comment by fkling** [comment]
@redak105, react-docgen only focuses on React components. If you want generic documentation for functions or classes you have to use another documentation generation tool.

**Comment by fkling** [comment]
Closing this since there hasn't been any activity.
