### ISSUE TITLE
support new prop-types package

### ISSUE THREAD

**Issue by oliviertassinari** [reactjs/react-docgen#171]
[Yesterday's announcement](https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html) includes a deprecation of `React.PropTypes` and an introduction of a new package `prop-types`.
That's change introduce breaking changes here, for instance, the `required` value is no longer correct.

**Comment by kazazor** [comment]
We're also seeing issues due to that. For example we're now getting this output:

prop | type | default | required | description
---- | :----: | :-------: | :--------: | -----------
**children** | `(custom validator)` |  | :x: | The components's children
**className** | `(custom validator)` |  | :x: | A custom CSS class name
**disabled** | `(custom validator)` |  | :x: | Whether the anchor is clickable or not
**hovered** | `(custom validator)` |  | :x: | Whether the button is in hover state
**onClick** | `(custom validator)` |  | :x: | A callback function for click event


While we used to get:

prop | type | default | required | description
---- | :----: | :-------: | :--------: | -----------
**children** | `ReactNode` |  | :white_check_mark: | The components's children
**className** | `String` |  | :x: | A custom CSS class name
**disabled** | `Boolean` |  | :x: | Whether the anchor is clickable or not
**hovered** | `Boolean` |  | :x: | Whether the button is in hover state
**onClick** | `Function` |  | :x: | A callback function for click event

So it's the `Required` & the `type` that does not work.

**Comment by fkling** [comment]
Publish in v2.14.0 and v3.0.0-beta3.
