### ISSUE TITLE
required field is always false

### ISSUE THREAD

**Issue by davidfirst** [reactjs/react-docgen#321]
I get `"required": false` also when I set my variable to be required, e.g. `PropTypes.number.isRequired`.

An example code
```
MyComponent.propTypes = {
  foo: PropTypes.number.isRequired,
};
```
I get
```
{
  "description": "General component description.",
  "displayName": "MyComponent",
  "methods": [],
  "props": {
    "foo": {
      "type": {
        "name": "number"
      },
      "required": false,
      "description": "",
      "defaultValue": {
        "value": "42",
        "computed": false
      }
    }
  }
}
```

**Comment by danez** [comment]
Which version of `react-docgen` are you using?

**Comment by davidfirst** [comment]
The latest. `3.0.0`.
The code I used is from the readme. (which by the way threw an error, until I replaced `render: function() {` with `render: () => {`.

**Comment by danez** [comment]
Thanks for reporting I was able to reproduce this.

**Comment by danez** [comment]
After inspecting, there is not really a problem. The confusion with the example comes because `foo` in that example has a default value. Props with a default value are never required even if `isRequired` is set. The problem is more, that the definition of the component is wrong. One should not use `isRequired` and then define a defaultValue.

I will fix the example.
