### ISSUE TITLE
"command not found: react-docgen"

### ISSUE THREAD

**Issue by robert-barcelona** [reactjs/react-docgen#326]
I added 'react-docgen' using 

`yarn add react-docgen --dev
`
and when I entered 

`react-docgen src`

I get

> command not found: react-docgen

I tried installing it globally, with the same result.

MacOS 10.14,  React 0.16

**Comment by danez** [comment]
If you add a dependency in your project you cannot simply call its binary in the library from your commandline. If you install it globally it should work if everything is setup correctly https://yarnpkg.com/lang/en/docs/cli/global/#adding-the-install-location-to-your-path.

If you installed the dependency in the project this is what you can do to run it:

1. You can use `yarn react-docgen --help` to run the cli
2. You could directly call the cli from its location `./node_modules/.bin/react-docgen --help`
3. In your package.json scripts you can directly use the binary because yarn/npm do correctly resolve them, for example:

```js
{
  ...
  "scripts": {
    "docu": "react-docgen --help"
  }
  ...
}
```

**Comment by jquense** [comment]
for `npm` client users `npx react-docgen` will also work for using the local binary
