### ISSUE TITLE
How to convert to HTML?

### ISSUE THREAD

**Issue by thealjey** [reactjs/react-docgen#37]
Sorry for a noob question, but how do I actually use this to generate normal human-readable documentation?
Also, if there is other non-react code on the project, will this also be able to document that?

**Comment by fkling** [comment]
Since the output is JSON, you can process the JSON in any way you want. E.g. you could pass it to your favorite HTML template engine or build the HTML manually.

In [`example/`](/reactjs/react-docgen/tree/master/example/) you will find some code that converts the JSON blob to Markdown (which in turn can be converted to HTML).
