### ISSUE TITLE
Support for builded code

### ISSUE THREAD

**Issue by ondrejbartas** [reactjs/react-docgen#40]
Hi I would love to use your package for extracting props from already builded code:

```
'use strict';

exports.__esModule = true;

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { 'default': obj }; }

var _react = require('react');

var _react2 = _interopRequireDefault(_react);

/**
  * Example component description
  */
var Component = function Component(props) {
  return _react2['default'].createElement('div', null);
};
Component.displayName = 'ABC';
Component.defaultProps = {
  foo: true
};
Component.propTypes = {
  /**
  * Example prop description
  */
  foo: _react.PropTypes.bool
};
exports['default'] = Component;
module.exports = exports['default'];    
```

I tried to do it, but i had problem with npm test which was returning:
```
Runtime Error
TypeError: react-docgen/tests/setupTestFramework.js: 
/react-docgen/node_modules/recast/main.js: 
react-docgen/node_modules/recast/lib/types.js: 
react-docgen/node_modules/ast-types/main.js: 
react-docgen/node_modules/ast-types/def/core.js: 
react-docgen/node_modules/ast-types/lib/shared.js: Cannot read property 'toString' of undefined
```

**Comment by fkling** [comment]
> I tried to do it

What exactly did you try?

> i had problem with npm test

I fixed the test setup in 546635c8c6e76aa70eb08e9f567652d67931fe5d .

**Comment by fkling** [comment]
Closing this, since I haven't heard back. I'm also not sure if we can do much here, since, in general, the shape of transpiled code is unknown and there may not be enough information to find the information we we want.

**Comment by just-boris** [comment]
Hello!

I have also tried to gather documentation for sources after Babel.
Currently, there is now a problem with `_interopRequireDefault` function:

Given the following code
```js
'use strict';

function _interopDefault (ex) { return (ex && (typeof ex === 'object') && 'default' in ex) ? ex['default'] : ex; }

var React = _interopDefault(require('react'));

function MyComponent(_ref) {
    var className = _ref.className,
        children = _ref.children,
        style = _ref.style;

    return React.createElement(
        'button',
        { className: className, style: style },
        children
    );
}

module.exports = MyComponent;
```

The problem here is that `React` identifier is recognized as a result of unknown `_interopDefault` function. I think it makes sense to check the arguments of the call, whether there is a `require` or not.
When I added [there](https://github.com/reactjs/react-docgen/blob/master/src/utils/resolveToModule.js#L37) also a check for arguments, it worked fine.

What do you think about fixing this?

**Comment by fkling** [comment]
@just-boris, why do you run react-docgen on compiled code? In general I don't think it makes sense to try to fix this since Babel removes a lot of the syntax that react-docgen uses to extract information. Just think about what classes are compiled to:

```js
class Foo extends React.Component {
 propTypes = {
   bar: React.PropTypes.string,
 };
}
```

becomes

```js
"use strict";

function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }

function _possibleConstructorReturn(self, call) { if (!self) { throw new ReferenceError("this hasn't been initialised - super() hasn't been called"); } return call && (typeof call === "object" || typeof call === "function") ? call : self; }

function _inherits(subClass, superClass) { if (typeof superClass !== "function" && superClass !== null) { throw new TypeError("Super expression must either be null or a function, not " + typeof superClass); } subClass.prototype = Object.create(superClass && superClass.prototype, { constructor: { value: subClass, enumerable: false, writable: true, configurable: true } }); if (superClass) Object.setPrototypeOf ? Object.setPrototypeOf(subClass, superClass) : subClass.__proto__ = superClass; }

var Foo = function (_React$Component) {
  _inherits(Foo, _React$Component);

  function Foo() {
    var _ref;

    var _temp, _this, _ret;

    _classCallCheck(this, Foo);

    for (var _len = arguments.length, args = Array(_len), _key = 0; _key < _len; _key++) {
      args[_key] = arguments[_key];
    }

    return _ret = (_temp = (_this = _possibleConstructorReturn(this, (_ref = Foo.__proto__ || Object.getPrototypeOf(Foo)).call.apply(_ref, [this].concat(args))), _this), _this.propTypes = {
      bar: React.PropTypes.string
    }, _temp), _possibleConstructorReturn(_this, _ret);
  }

  return Foo;
}(React.Component);
```

I'd think this becomes impossible to reliably extract information from.

**Comment by just-boris** [comment]
Well, of course, if I could run Docgen on top of source code, I did it... 

In my case, the problem is that build process for files is a bit complex. I am trying to build documentation using [React-styleguidist](https://github.com/styleguidist/react-styleguidist), it requires me to use Webpack, but the project is built with Rollup, so I have to either, maintain the second version of configuration with Webpack loaders, or just generate documentation based on built files.

Also, to define propTypes, you need to add as `static` property, and then Babel will write it like 

```js
var Foo = function (_React$Component) {
  _inherits(Foo, _React$Component);

  function Foo() {
    _classCallCheck(this, Foo);

    return _possibleConstructorReturn(this, (Foo.__proto__ || Object.getPrototypeOf(Foo)).apply(this, arguments));
  }

  return Foo;
}(React.Component);

Foo.propTypes = {
  bar: React.PropTypes.string
};
```
Which is recongizable by React-docgen right now.

I have already built a styleguide with modified version of React-docgen, and the only problem, that I have found was about unrecognized React `require`.
