### ISSUE TITLE
Support ES6 Static Getters

### ISSUE THREAD

**Issue by kcjonson** [reactjs/react-docgen#61]
Forgive me if I'm wrong on this one, but react-docgen does not appear to support static getters in ES6 classes at the moment.  Would be awesome if it did.  If Im reading the docs right, this is simply a new _resolver_ and the existing _handlers_ can be reused?

```javascript
static get displayName() {
	return "button";
}

static get defaultProps() {
	return {
		type: "primary",
	};
}
```

**Comment by fkling** [comment]
> If Im reading the docs right, this is simply a new resolver and the existing handlers can be reused?

Not quite. Resolvers just find component definitions. They don't extract any information. Handlers are functions which get passed the found component definitions and extract the information.

But also here, we tried to make everything transparent so that handlers don't have to care what kind of component definitions they get (class, stateless, etc).

However, looking at the code, this should already work for, for `defaultProps` at least. `displayName` needs to be updated to look into functions.
