### ISSUE TITLE
Recommendations for integrating with Sphinx

### ISSUE THREAD

**Issue by woodb** [reactjs/react-docgen#7]
I was wondering if there were any recommendations or gists out there for using this in conjunction with [Sphinx](http://sphinx-doc.org/)?

**Comment by fkling** [comment]
I'm not familiar with Sphinx, but at a first glance, you might want to look at the ["JavaScript domain"](http://sphinx-doc.org/domains.html#the-javascript-domain).

Instead of e.g. generating markdown from the result JSON/JS object (as shown in the [example](https://github.com/reactjs/react-docgen/blob/master/example/generateMarkdown.js)), you would generate an output that conforms to that syntax and then feed it to Sphinx.

If someone more familiar with Sphinx wants to provide a generator that does that, I'm more than happy to link to it in the wiki*.

---

*: We could have a wiki page that links to tools which can consume the output of react-docgen.

**Comment by woodb** [comment]
Ah sweet! I didn't see the markdown generator. Sphinx prefers reStructuredText, so maybe the most reasonable way to implement this would be to simply make a generator that produces rST... I'll try my hand at it and keep you apprised, thanks.

**Comment by fkling** [comment]
Awesome :+1: 

I'm not familiar with reStructuredText either, but yes, if Sphinx can work with any reStructuredText, that would work as well!

Also keep in mind that you can use any "markup" language in the component and prop types *comments* as long as your conversion process understands it.

----

In general, I think it's more useful if any step produces a rather generic intermediated format that can be consumed by other tools. That's why react-docgen produces JSON and not markdown for example. Similar here, if one creates a converter to reStructuredText, any tool that can consume reStructuredText can be used, not just Sphinx.

**Comment by woodb** [comment]
Thanks @fkling, closing this one following the creation #8.
