### ISSUE TITLE
Redux connect support

### ISSUE THREAD

**Issue by maximelebastard** [reactjs/react-docgen#80]
Hi,

I have a React/Redux app that I'd like to document. With redux, I use the [connect()](https://github.com/reactjs/react-redux/blob/master/docs/api.md) function.

But when I use it, react-docgen cannot find a valid component in my file.

This works:

````
const Contributors = React.createClass({...});
export default Contributors;
````

This does not:

```
const Contributors = React.createClass({...});
const mapStateToProps = (state) => {
  return { contributors: state.contributors }
}
export default connect(mapStateToProps)(Contributors);
```

I found a workaround by appending this to the end of file, but I don't know if it will not break something later:

```
module.exports = Contributors;
```

**Comment by rtsao** [comment]
I've run into this issue as well. I've added support for single unary higher-order-components in my fork. This is the relevant commit here: https://github.com/rtsao/react-docgen/commit/46ec8dfedc323ff1608229ae8d1c3064669455d4

You can turn your code to use a single unary higher-order component like so:

```js
const Contributors = React.createClass({...});
const mapStateToProps = (state) => {
  return { contributors: state.contributors }
}

const hoc = (Component) => connect(mapStateToProps)(Component);

export default hoc(Contributors);
```

The above code will work with my fork.

If multiple higher order components are needed, you can use [recompose](https://github.com/acdlite/recompose)'s `compose` helper.

I think **only** supporting a single unary higher-order component seems like a reasonable compromise, since basically you can convert all forms of higher-order component composition into that form. Supporting multiple call expressions seems like you could quickly go down a rabbit hole.

I'd be happy to create a PR if @fkling thinks my approach is reasonable.

**Comment by fkling** [comment]
@rtsao:

> I've added support for single unary higher-order-components in my personal fork

That seems very reasonable to me, and I think it would even make sense to expand this to non-unary functions. The other arguments could be included in the output as well, as far as possible. Happy to review that PR :)

@maximelebastard
As an intermediate solution, if you can use the `findAllComponentDefinitions` resolver, which looks for all component definitions, not just the exported ones.

**Comment by tizmagik** [comment]
@rtsao that looks very useful! Was a PR ever submitted for this?

**Comment by rtsao** [comment]
Yeah, actually I think this should be very doable.

```js
export default hoc1(Component);

export default hoc1(arg1a, arg1b)(Component);

export default hoc2(arg2b, arg2b)(
  hoc1(arg1a, arg2a)(Component)
);

export default hoc3(arg3a, arg3b)(
  hoc2(arg2b, arg2b)(
    hoc1(arg1a, arg2a)(Component)
  )
);

// etc...

```

**Comment by rtsao** [comment]
I've implemented this here: https://github.com/reactjs/react-docgen/pull/124
